PGAdmin documentation
OpenEnergyDashboard/OpenEnergyDashboard.github.io pull request #58
Opened 2024-05-07 04:02 UTC by AdityaMSaraf

Added description on how to use the pgAdmin utility as another way to access the database in developer documentation.

2024-05-07 14:12 UTC, huss requested changes
Thanks to @AdityaMSaraf for this contribution. I have made a few comments to address.

2024-05-07 14:12 UTC, huss commented on developer/devDetails.html
> +	<p>There are two ways to access the Postgres database that OED uses. Through the docker container or through pgAdmin
Maybe add a colon (:) at the end of the line.

2024-05-07 14:12 UTC, huss commented on developer/devDetails.html
>  	<p>You can access the Postgres database that OED uses within the docker container. In the database docker container
This now duplicates the bullet above. I propose to remove this paragraph. Then add to the end of the second bullet that this directly accesses the OED database as noted in first bullet.

2024-05-08 19:08 UTC, AdityaMSaraf commented on developer/devDetails.html
> +	<p>There are two ways to access the Postgres database that OED uses. Through the docker container or through pgAdmin
Added

2024-05-08 19:08 UTC, AdityaMSaraf commented on developer/devDetails.html
>  	<p>You can access the Postgres database that OED uses within the docker container. In the database docker container
Removed paragraph following the bullets and added information to first two bullets

2024-05-09 14:36 UTC, huss approved these changes
Thanks to @AdityaMSaraf  for the changes. They were okay but I decided to enhance the directions somewhat. With this, the PR is ready to merge.

2024-05-09 14:36 UTC, merged